pipeline {
    agent any

    stages {
        stage('Pull code') {
            steps {
                git branch: 'main', url: 'https://github.com/kunskun/devtool-final-2022'
            }
        }
        stage('Download dependency') {
            steps {
                sh 'cd backend && mpn install'
            }
        }
        stage('Run Unit test') {
            steps {
                echo 'unit test'
            }
        }
        stage('Run Component test') {
            steps {
                echo 'coverage test'
            }
        }
        stage('Deployment') {
            steps {
                echo 'deploy'
        //         withCredentials([
        //             usernamePassword(credentialsId: 'username-password-ssh', passwordVariable: 'password', usernameVariable: 'user_name'), 
        //             string(credentialsId: 'backend-host', variable: 'host_ip'), string(credentialsId: 'host_name', variable: 'host_name'), 
        //             usernamePassword(credentialsId: 'team-5-dockerhub', passwordVariable: 'docker_password', usernameVariable: 'docker_username')]) {
        //             script{
        //                 def remote = [:]
        //                 remote.name = host_name
        //                 remote.host = host_ip
        //                 remote.user = user_name
        //                 remote.password = password
        //                 remote.allowAnyHosts = true
                        
        //                 sshCommand remote: remote, command: "git clone https://github.com/peetnawapol/project-01-software-dev-tool"
        //                 sshCommand remote: remote, command: "docker-compose -f project-01-software-dev-tool/docker-compose-build.yml build server-side"
                        
        //                 sshCommand remote: remote, command: "docker login -u $docker_username -p $docker_password"
        //                 sshCommand remote: remote, command: "docker push thanayutks/team-05-backend:1.0.0"
        //                 sshCommand remote: remote, command: "docker image rmi -f thanayutks/team-05-backend:1.0.0"
                        
        //                 sshCommand remote: remote, command: "docker pull thanayutks/team-05-backend:1.0.0"
        //                 sshCommand remote: remote, command: "docker logout"
        //                 sshCommand remote: remote, command: "docker-compose -f project-01-software-dev-tool/docker-compose-deploy.yml up -d server-side"
        //                 sshCommand remote: remote, command: "rm -r project-01-software-dev-tool"
        //             }
        //         }
        //     }
        //     post{
        //         failure{
        //             script{
        //                 def testing = build job: "team-5-backend"
        //                 sh '$testing.getNumber()'
        //             }
        //             withCredentials([gitUsernamePassword(credentialsId: 'team-5-github', gitToolName: 'Default')]) {
        //             sh 'git tag -d ' + '1.0.'+ $testing.getNumber()
        //             }
                        
        //         }
            }
        }
        stage('Run E2E test') {
            steps {
                echo 'E2E test'
            }
        }
    }
}